export const ACTION_ID =
  process.env.WLD_ACTION_ID || "wid_staging_3b023904babb53b039973b9341d2b5b7";

export const PRE_COMMIT_MANAGER_ADDRESS = {
  5001: "0x80F7b90C88A80eE1e60e74Ce0c6207DfcA2E182C",
  5: "0x1550A951Eb4a59cb1a92e231951A63e7C6936057",
};

export const USDC_DUMMY = {
  5001: "0x7D26526DedC4C3aB56B2d652AE5a75181D92bd2c",
  5: "0x07865c6e87b9f70255377e024ace6630c1eaa37f",
};

export const BACKEND_LINKS = Object.freeze({
  // Mumbai
  5001: {
    theGraph:
      "https://api.thegraph.com/subgraphs/name/nhausman1/modular-microloans",
  },
  // Goerli
  5: {
    theGraph:
      "https://api.thegraph.com/subgraphs/name/nhausman1/goerli-modular-microloans",
  },
  // Optimism
  //   5: {
  //     theGraph:
  //       "https://api.thegraph.com/subgraphs/name/nhausman1/goerli-modular-microloans",
  //   },
});

export const COUNTRY_LIST = [
  { label: "Argentina 🇦🇷", id: "032" },
  { label: "Belize 🇧🇿", id: "084" },
  { label: "Bolivia 🇧🇴", id: "068" },
  { label: "Brazil 🇧🇷", id: "076" },
  { label: "Chile 🇨🇱", id: "152" },
  { label: "Colombia 🇨🇴", id: "170" },
  { label: "Costa Rica 🇨🇷", id: "188" },
  { label: "Cuba 🇨🇺", id: "192" },
  { label: "Dominican Republic 🇩🇴", id: "214" },
  { label: "Ecuador 🇪🇨", id: "218" },
  { label: "El Salvador 🇸🇻", id: "222" },
  { label: "Guatemala 🇬🇹", id: "320" },
  { label: "Haiti 🇭🇹", id: "332" },
  { label: "Honduras 🇭🇳", id: "340" },
  { label: "Jamaica 🇯🇲", id: "388" },
  { label: "Mexico 🇲🇽", id: "484" },
  { label: "Nicaragua 🇳🇮", id: "558" },
  { label: "Panama 🇵🇦", id: "591" },
  { label: "Paraguay 🇵🇾", id: "600" },
  { label: "Peru 🇵🇪", id: "604" },
  { label: "Saint Lucia 🇱🇨", id: "662" },
  { label: "Uruguay 🇺🇾", id: "858" },
  { label: "Venezuela 🇻🇪", id: "862" },
  { label: "Afghanistan", id: "004" },
  { label: "Albania", id: "008" },
  { label: "Algeria", id: "012" },
  { label: "American Samoa", id: "016" },
  { label: "Andorra", id: "020" },
  { label: "Angola", id: "024" },
  { label: "Anguilla", id: "660" },
  { label: "Antarctica", id: "010" },
  { label: "Antigua and Barbuda", id: "028" },
  { label: "Armenia", id: "051" },
  { label: "Aruba", id: "533" },
  { label: "Australia", id: "036" },
  { label: "Austria", id: "040" },
  { label: "Azerbaijan", id: "031" },
  { label: "Bahamas (the)", id: "044" },
  { label: "Bahrain", id: "048" },
  { label: "Bangladesh", id: "050" },
  { label: "Barbados", id: "052" },
  { label: "Belarus", id: "112" },
  { label: "Belgium", id: "056" },
  { label: "Benin", id: "204" },
  { label: "Bermuda", id: "060" },
  { label: "Bhutan", id: "064" },
  { label: "Bonaire, Sint Eustatius and Saba", id: "535" },
  { label: "Bosnia and Herzegovina", id: "070" },
  { label: "Botswana", id: "072" },
  { label: "Bouvet Island", id: "074" },
  { label: "British Indian Ocean Territory (the)", id: "086" },
  { label: "Brunei Darussalam", id: "096" },
  { label: "Bulgaria", id: "100" },
  { label: "Burkina Faso", id: "854" },
  { label: "Burundi", id: "108" },
  { label: "Cabo Verde", id: "132" },
  { label: "Cambodia", id: "116" },
  { label: "Cameroon", id: "120" },
  { label: "Canada", id: "124" },
  { label: "Cayman Islands (the)", id: "136" },
  { label: "Central African Republic (the)", id: "140" },
  { label: "Chad", id: "148" },
  { label: "China", id: "156" },
  { label: "Christmas Island", id: "162" },
  { label: "Cocos (Keeling) Islands (the)", id: "166" },
  { label: "Comoros (the)", id: "174" },
  { label: "Congo (the Democratic Republic of the)", id: "180" },
  { label: "Congo (the)", id: "178" },
  { label: "Cook Islands (the)", id: "184" },
  { label: "Croatia", id: "191" },
  { label: "Curaçao", id: "531" },
  { label: "Cyprus", id: "196" },
  { label: "Czechia", id: "203" },
  { label: "Côte d'Ivoire", id: "384" },
  { label: "Denmark", id: "208" },
  { label: "Djibouti", id: "262" },
  { label: "Dominica", id: "212" },
  { label: "Egypt", id: "818" },
  { label: "Equatorial Guinea", id: "226" },
  { label: "Eritrea", id: "232" },
  { label: "Estonia", id: "233" },
  { label: "Eswatini", id: "748" },
  { label: "Ethiopia", id: "231" },
  { label: "Falkland Islands (the) [Malvinas]", id: "238" },
  { label: "Faroe Islands (the)", id: "234" },
  { label: "Fiji", id: "242" },
  { label: "Finland", id: "246" },
  { label: "France", id: "250" },
  { label: "French Guiana", id: "254" },
  { label: "French Polynesia", id: "258" },
  { label: "French Southern Territories (the)", id: "260" },
  { label: "Gabon", id: "266" },
  { label: "Gambia (the)", id: "270" },
  { label: "Georgia", id: "268" },
  { label: "Germany", id: "276" },
  { label: "Ghana", id: "288" },
  { label: "Gibraltar", id: "292" },
  { label: "Greece", id: "300" },
  { label: "Greenland", id: "304" },
  { label: "Grenada", id: "308" },
  { label: "Guadeloupe", id: "312" },
  { label: "Guam", id: "316" },
  { label: "Guernsey", id: "831" },
  { label: "Guinea", id: "324" },
  { label: "Guinea-Bissau", id: "624" },
  { label: "Guyana", id: "328" },
  { label: "Heard Island and McDonald Islands", id: "334" },
  { label: "Holy See (the)", id: "336" },
  { label: "Hong Kong", id: "344" },
  { label: "Hungary", id: "348" },
  { label: "Iceland", id: "352" },
  { label: "India", id: "356" },
  { label: "Indonesia", id: "360" },
  { label: "Iran (Islamic Republic of)", id: "364" },
  { label: "Iraq", id: "368" },
  { label: "Ireland", id: "372" },
  { label: "Isle of Man", id: "833" },
  { label: "Israel", id: "376" },
  { label: "Italy", id: "380" },
  { label: "Japan", id: "392" },
  { label: "Jersey", id: "832" },
  { label: "Jordan", id: "400" },
  { label: "Kazakhstan", id: "398" },
  { label: "Kenya", id: "404" },
  { label: "Kiribati", id: "296" },
  {
    label: "Korea (the Democratic People's Republic of) ",
    id: "408",
  },
  { label: "Korea (the Republic of)", id: "410" },
  { label: "Kuwait", id: "414" },
  { label: "Kyrgyzstan", id: "417" },
  {
    label: "Lao People's Democratic Republic(the)",
    id: "418",
  },
  { label: "Latvia", id: "428" },
  { label: "Lebanon", id: "422" },
  { label: "Lesotho", id: "426" },
  { label: "Liberia", id: "430" },
  { label: "Libya", id: "434" },
  { label: "Liechtenstein", id: "438" },
  { label: "Lithuania", id: "440" },
  { label: "Luxembourg", id: "442" },
  { label: "Macao", id: "446" },
  { label: "Madagascar", id: "450" },
  { label: "Malawi", id: "454" },
  { label: "Malaysia", id: "458" },
  { label: "Maldives", id: "462" },
  { label: "Mali", id: "466" },
  { label: "Malta", id: "470" },
  { label: "Marshall Islands (the)", id: "584" },
  { label: "Martinique", id: "474" },
  { label: "Mauritania", id: "478" },
  { label: "Mauritius", id: "480" },
  { label: "Mayotte", id: "175" },
  { label: "Micronesia (Federated States of)", id: "583" },
  { label: "Moldova (the Republic of)", id: "498" },
  { label: "Monaco", id: "492" },
  { label: "Mongolia", id: "496" },
  { label: "Montenegro", id: "499" },
  { label: "Montserrat", id: "500" },
  { label: "Morocco", id: "504" },
  { label: "Mozambique", id: "508" },
  { label: "Myanmar", id: "104" },
  { label: "Namibia", id: "516" },
  { label: "Nauru", id: "520" },
  { label: "Nepal", id: "524" },
  { label: "Netherlands (the)", id: "528" },
  { label: "New Caledonia", id: "540" },
  { label: "New Zealand", id: "554" },
  { label: "Niger (the)", id: "562" },
  { label: "Nigeria", id: "566" },
  { label: "Niue", id: "570" },
  { label: "Norfolk Island", id: "574" },
  { label: "Northern Mariana Islands (the)", id: "580" },
  { label: "Norway", id: "578" },
  { label: "Oman", id: "512" },
  { label: "Pakistan", id: "586" },
  { label: "Palau", id: "585" },
  { label: "Palestine, State of", id: "275" },
  { label: "Papua New Guinea", id: "598" },
  { label: "Philippines (the)", id: "608" },
  { label: "Pitcairn", id: "612" },
  { label: "Poland", id: "616" },
  { label: "Portugal", id: "620" },
  { label: "Puerto Rico", id: "630" },
  { label: "Qatar", id: "634" },
  { label: "Republic of North Macedonia", id: "807" },
  { label: "Romania", id: "642" },
  { label: "Russian Federation (the)", id: "643" },
  { label: "Rwanda", id: "646" },
  { label: "Réunion", id: "638" },
  { label: "Saint Barthélemy", id: "652" },
  { label: "Saint Helena, Ascension and Tristan da Cunha", id: "654" },
  { label: "Saint Kitts and Nevis", id: "659" },
  { label: "Saint Martin (French part)", id: "663" },
  { label: "Saint Pierre and Miquelon", id: "666" },
  { label: "Saint Vincent and the Grenadines", id: "670" },
  { label: "Samoa", id: "882" },
  { label: "San Marino", id: "674" },
  { label: "Sao Tome and Principe", id: "678" },
  { label: "Saudi Arabia", id: "682" },
  { label: "Senegal", id: "686" },
  { label: "Serbia", id: "688" },
  { label: "Seychelles", id: "690" },
  { label: "Sierra Leone", id: "694" },
  { label: "Singapore", id: "702" },
  { label: "Sint Maarten (Dutch part)", id: "534" },
  { label: "Slovakia", id: "703" },
  { label: "Slovenia", id: "705" },
  { label: "Solomon Islands", id: "090" },
  { label: "Somalia", id: "706" },
  { label: "South Africa", id: "710" },
  { label: "South Georgia and the South Sandwich Islands", id: "239" },
  { label: "South Sudan", id: "728" },
  { label: "Spain", id: "724" },
  { label: "Sri Lanka", id: "144" },
  { label: "Sudan (the)", id: "729" },
  { label: "Suriname", id: "740" },
  { label: "Svalbard and Jan Mayen", id: "744" },
  { label: "Sweden", id: "752" },
  { label: "Switzerland", id: "756" },
  { label: "Syrian Arab Republic", id: "760" },
  { label: "Taiwan", id: "158" },
  { label: "Tajikistan", id: "762" },
  { label: "Tanzania, United Republic of", id: "834" },
  { label: "Thailand", id: "764" },
  { label: "Timor-Leste", id: "626" },
  { label: "Togo", id: "768" },
  { label: "Tokelau", id: "772" },
  { label: "Tonga", id: "776" },
  { label: "Trinidad and Tobago", id: "780" },
  { label: "Tunisia", id: "788" },
  { label: "Turkey", id: "792" },
  { label: "Turkmenistan", id: "795" },
  { label: "Turks and Caicos Islands (the)", id: "796" },
  { label: "Tuvalu", id: "798" },
  { label: "Uganda", id: "800" },
  { label: "Ukraine", id: "804" },
  { label: "United Arab Emirates (the)", id: "784" },
  {
    label: "United Kingdom of Great Britain and Northern Ireland (the)",
    id: "826",
  },
  { label: "United States Minor Outlying Islands (the)", id: "581" },
  { label: "United States of America (the)", id: "840" },
  { label: "Uruguay", id: "858" },
  { label: "Uzbekistan", id: "860" },
  { label: "Vanuatu", id: "548" },
  { label: "Viet Nam", id: "704" },
  { label: "Virgin Islands (British)", id: "092" },
  { label: "Virgin Islands (U.S.)", id: "850" },
  { label: "Wallis and Futuna", id: "876" },
  { label: "Western Sahara", id: "732" },
  { label: "Yemen", id: "887" },
  { label: "Zambia", id: "894" },
  { label: "Zimbabwe", id: "716" },
  { label: "Åland Islands", id: "248" },
];
